package com.example.adminservice.entity.enums;

/**
 * @author Sanjarbek Allayev, пт 7:40. 15.04.2022
 */
public enum RegionEnum {
    BOSHQA,
    ANDIJON_VILOYATI,
    BUXORO_VILOYATI,
    NAVOIY_VILOYATI,
    XORAZM_VILOYATI,
    TOSHKENT_VILOYATI,
    TOSHKENT_SHAHRI,
    SAMARQAND_VILOYATI,
    QASHQADARYO_VILOYATI,
    SURXONDARYO_VILOYATI,
    JIZZAX_VILOYATI,
    FARGONA_VILOYATI,
    NAMANGAN_VILOYATI,
    QORAQALPOGISTON_RESPUBLIKASI,
    SIRDARYO_VILOYATI

}
